another commit

diff --git a/projects/collatz/makefile b/projects/collatz/makefile
--- a/projects/collatz/makefile
+++ b/projects/collatz/makefile
@@ -38,9 +38,9 @@ html: Doxyfile Collatz.h Collatz.c++ RunCollatz.c++ TestCollatz.c++
 
 check:
 	@for i in $(FILES);                                         \
-    do                                                          \
-        [ -e $$i ] && echo "$$i found" || echo "$$i NOT FOUND"; \
-    done
+	do                                                          \
+		[ -e $$i ] && echo "$$i found" || echo "$$i NOT FOUND"; \
+	done
 
 clean:
 	rm -f *.gcda
